name: Pull Request Check

# Controls when the workflow will run
on:
  # Triggers the workflow only on push to the main branch (and temorarily to branch that is introducing it)
  pull_request:
    branches:
      - main


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-20.04  # Need to use this version since  splunk slim package has outdated code for python >= 3.10

    steps:
      - uses: actions/checkout@v2

      - name: Install build dependencies
        run: |
          pip install https://download.splunk.com/misc/packaging-toolkit/splunk-packaging-toolkit-1.0.1.tar.gz

      - name: Set patch version
        run: |
          patch=$(TZ=UTC0 git show -s --date=format-local:'%Y%m%d%H%M' --format=%cd)
          echo "Patch version is $patch"
          sed -ri "s/\"version\": \"([0-9]+\\.[0-9]+)\\.[0-9]+\"/\"version\": \"\\1.$patch\"/" app/redhat_insights/app.manifest
          sed -ri "s/version = ([0-9]+\\.[0-9]+)\\.[0-9]+/version = \\1.$patch/" app/redhat_insights/default/app.conf

      - name: Set build version
        run: |
          old_build_ver=`grep "build" app/redhat_insights/default/app.conf | cut -d '=' -f 2`
          echo "Old Build version is $old_build_ver"
          new_build_ver=$((old_build_ver+1))
          echo "New Build version is $new_build_ver"
          sed -ri "s/build = [0-9]+/build = $new_build_ver/" app/redhat_insights/default/app.conf

      - name: Add branding assets
        run: |
          git clone https://github.com/RedHatInsights/frontend-assets.git
          rm app/redhat_insights/static/.keep
          cp frontend-assets/src/eventing-splunk-app/*.* app/redhat_insights/static/
          mv app/redhat_insights/static/favicon.ico app/redhat_insights/appserver/static/

      - name: Create package
        run: |
          mkdir build
          slim package app/redhat_insights -o build/
          SLIM_RESULT_FILE=$(ls -p build/ | grep -v /)
          echo "PACKAGE_FILENAME=$SLIM_RESULT_FILE" >> $GITHUB_ENV
          echo "${{ env.PACKAGE_FILENAME }}"

      - name: Run App Inspect CLI
        uses: splunk/appinspect-cli-action@v1
        with:
          app_path: build/${{ env.PACKAGE_FILENAME }}
          included_tags: cloud, splunk_appinspect
